const FETCH_NEWS_REQUEST = 'news/FETCH_NEWS_REQUEST';
const FETCH_NEWS_SUCCESS = 'news/FETCH_NEWS_SUCCESS';
const FETCH_NEWS_FAILURE = 'news/FETCH_NEWS_FAILURE';

export default {
  FETCH_NEWS_REQUEST,
  FETCH_NEWS_SUCCESS,
  FETCH_NEWS_FAILURE
};