const LOAD_PROFILE_DATA_REQUEST = 'profile/LOAD_PROFILE_DATA_REQUEST';
const LOAD_PROFILE_DATA_SUCCESS = 'profile/LOAD_PROFILE_DATA_SUCCESS';
const LOAD_PROFILE_DATA_FAILURE = 'profile/LOAD_PROFILE_DATA_FAILURE';

export default {
    LOAD_PROFILE_DATA_REQUEST,
    LOAD_PROFILE_DATA_SUCCESS,
    LOAD_PROFILE_DATA_FAILURE
};