const FETCH_PROFILE_DATA_REQUEST = 'profile/FETCH_PROFILE_DATA_REQUEST';
const FETCH_PROFILE_DATA_SUCCESS = 'profile/FETCH_PROFILE_DATA_SUCCESS';
const FETCH_PROFILE_DATA_FAILURE = 'profile/FETCH_PROFILE_DATA_FAILURE';

export default {
    FETCH_PROFILE_DATA_REQUEST,
    FETCH_PROFILE_DATA_SUCCESS,
    FETCH_PROFILE_DATA_FAILURE
};